//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure.ApiManagement.IngestTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azure.ApiManagement.IngestTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap API_Management {
            get {
                object obj = ResourceManager.GetObject("API_Management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Service.
        /// </summary>
        internal static string ConSvcCategory {
            get {
                return ResourceManager.GetString("ConSvcCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import REST APIs into Azure API Management so you can manage and monitor their usage.
        /// </summary>
        internal static string ConSvcDescription {
            get {
                return ResourceManager.GetString("ConSvcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure API Management Importer.
        /// </summary>
        internal static string ConSvcName {
            get {
                return ResourceManager.GetString("ConSvcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrivieving Swagger.
        /// </summary>
        internal static string FinishWizardUploadSwagger {
            get {
                return ResourceManager.GetString("FinishWizardUploadSwagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing API into API Management.
        /// </summary>
        internal static string ImportMessage {
            get {
                return ResourceManager.GetString("ImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing an API into Azure API Management.
        /// </summary>
        internal static string ImportToProducts {
            get {
                return ResourceManager.GetString("ImportToProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source API App.
        /// </summary>
        internal static string Page1Legend {
            get {
                return ResourceManager.GetString("Page1Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import REST APIs into Azure API Management so you can manage and monitor their usage.
        /// </summary>
        internal static string Page1Subtitle {
            get {
                return ResourceManager.GetString("Page1Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST API Metadata Source.
        /// </summary>
        internal static string Page1Title {
            get {
                return ResourceManager.GetString("Page1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination API Management.
        /// </summary>
        internal static string Page2Legend {
            get {
                return ResourceManager.GetString("Page2Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import REST APIs into Azure API Management so you can manage and monitor their usage.
        /// </summary>
        internal static string Page2Subtitle {
            get {
                return ResourceManager.GetString("Page2Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Management Destination.
        /// </summary>
        internal static string Page2Title {
            get {
                return ResourceManager.GetString("Page2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding API {0} to Product {1}.
        /// </summary>
        internal static string ProgressMessageAddingApiToProductTemplate {
            get {
                return ResourceManager.GetString("ProgressMessageAddingApiToProductTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing the Swagger metadata from API App {0} into API Management Instance {1}.
        /// </summary>
        internal static string ProgressMessageImportingSwaggerTemplate {
            get {
                return ResourceManager.GetString("ProgressMessageImportingSwaggerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving API Apps.
        /// </summary>
        internal static string WaitMessageGettingApiApps {
            get {
                return ResourceManager.GetString("WaitMessageGettingApiApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving API Management Instances.
        /// </summary>
        internal static string WaitMessageGettingApimList {
            get {
                return ResourceManager.GetString("WaitMessageGettingApimList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Swagger metadata.
        /// </summary>
        internal static string WaitMessageGettingSwagger {
            get {
                return ResourceManager.GetString("WaitMessageGettingSwagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving API Management products.
        /// </summary>
        internal static string WaitMessageRetrievingProductList {
            get {
                return ResourceManager.GetString("WaitMessageRetrievingProductList", resourceCulture);
            }
        }
    }
}
